### ISSUE TITLE
test_communication failure due to the improper publisher error handling after the zenoh session is closed

### ISSUE THREAD

**Issue by YuanYuYuan** [ZettaScaleLabs/rmw_zenoh#25] opened 2024-09-30 15:43 UTC
```console
/workspace/build/test_communication/test_publisher_cpp UnboundedSequences /test_time_09_24_23

[INFO] [rmw_zenoh_cpp]: Successfully connected to a Zenoh router with id 88063b2d82181eef79993539dc8c285b. (operator()() at 35)
publishing message #1
publishing message #2
publishing message #3
publishing message #4
publishing message #5
publishing message #1
publishing message #2
publishing message #3
publishing message #4
publishing message #5
publishing message #1
publishing message #2
publishing message #3
publishing message #4
publishing message #5
publishing message #1
publishing message #2
^C[INFO] [rclcpp]: signal_handler(signum=2) (signal_handler() at 71)
2024-09-30T15:11:42.098853Z  INFO ThreadId(11) zenoh::api::session: close session zid=767fb74255a4315dffa6767c7135bd2e
publishing message #3
2024-09-30T15:11:42.225308Z ERROR ThreadId(02) zenohcd::publisher: session closed at /workspace/src/zenoh/zenoh/src/api/session.rs:188.
ERROR: got unexpected exception: failed to publish message: unable to publish message, at /workspace/src/rmw_zenoh/rmw_zenoh_cpp/src/rmw_zenoh.cpp:946, at ./src/rcl/publisher.c:284
terminate called after throwing an instance of 'std::exception'
  what():  std::exception
./debug.sh: line 54: 1477287 Aborted                 (core dumped) /workspace/build/test_communication/test_publisher_cpp UnboundedSequences /test_time_09_24_23
```

The issue is we treat any publisher error as RMW_RET_ERROR in 

```cpp
  if (z_publisher_put(z_loan(publisher_data->pub), z_move(payload), &options) != Z_OK) {
    RMW_SET_ERROR_MSG("unable to publish message");
    return RMW_RET_ERROR;
  }
```

In 1.0, the publisher is possibly called after the session is closed. The Rust API can detect the closed session and then return an error. The question is how we properly handle this error in rmw_zenoh_cpp. The [RMW doc](https://docs.ros.org/en/rolling/p/rmw/generated/function_rmw_8h_1ab625a62ba2f32e3d3a7c7ca1f6e0dbd6.html#_CPPv411rmw_publishPK15rmw_publisher_tPKvP26rmw_publisher_allocation_t) does not seem to consider any errors like disconnection. 

To address the infallible rmw_publish, we could check if the session is alive whenever we fail to publish. If the session has been closed, then we simply ignore the error in rmw_publish.

**Comment by YuanYuYuan** [comment] 2024-09-30 15:45
Waiting for this function to be implemented in zenoh-c

https://github.com/eclipse-zenoh/zenoh-c/issues/727

**Comment by evshary** [comment] 2024-10-03 04:02
There are still errors in `test_communication` after the issue is fixed. :cry:

**Comment by imstevenpmwork** [comment] 2024-10-06 22:28
Can we close this now?

**Comment by YuanYuYuan** [comment] 2024-10-07 12:52
Yes it has been fixed

**Closed as completed** 2024-10-07 12:53 UTC
